"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var express_validator_1 = require("express-validator");
var date_Handler_1 = require("./handlers/date.Handler");
var cloudinaryTrabajos_1 = require("./config/cloudinaryTrabajos");
var middleware_1 = require("./middleware");
var router = (0, express_1.Router)();
router.get("/barberos", date_Handler_1.getBarberos);
router.post("/barberos", (0, express_validator_1.body)("barberos").isArray(), middleware_1.handlerInputErrors, date_Handler_1.saveBarberos);
router.get("/availability/:barber", (0, express_validator_1.param)("barber").notEmpty().trim(), middleware_1.handlerInputErrors, date_Handler_1.getBarberAvailability);
router.get("/trabajos", date_Handler_1.getTrabajos);
router.post("/trabajos", cloudinaryTrabajos_1.uploadTrabajo.single("archivo"), date_Handler_1.createTrabajo);
router.delete("/trabajos/:id", (0, express_validator_1.param)("id").isInt(), middleware_1.handlerInputErrors, date_Handler_1.deleteTrabajo);
router.post("/", (0, express_validator_1.body)("service").notEmpty(), (0, express_validator_1.body)("price").notEmpty().isNumeric().custom(function (v) { return parseFloat(v) >= 0; }), (0, express_validator_1.body)("barber").isString().notEmpty().trim(), (0, express_validator_1.body)("dateList").notEmpty(), (0, express_validator_1.body)("client").notEmpty(), (0, express_validator_1.body)("phone").notEmpty(), (0, express_validator_1.body)("duration").isNumeric().notEmpty(), middleware_1.handlerInputErrors, date_Handler_1.createProduct);
router.get("/:id", (0, express_validator_1.param)("id").isInt(), middleware_1.handlerInputErrors, date_Handler_1.getProductById);
router.put("/:id", (0, express_validator_1.param)("id").isInt(), middleware_1.handlerInputErrors, date_Handler_1.UpdateProduct);
router.patch("/:id", (0, express_validator_1.param)("id").isInt(), middleware_1.handlerInputErrors, date_Handler_1.updateAvailability);
router.delete("/:id", (0, express_validator_1.param)("id").isInt(), middleware_1.handlerInputErrors, date_Handler_1.deleteProduct);
exports.default = router;
